// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybtulljfdziyiopnssoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidHVsbGpmZHppeWlvcG5zc29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDg2NTksImV4cCI6MjA2NTU4NDY1OX0._RYtUGlWthlafm9dhBjcCacTIFGk0SVoW4nlyB_2aeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);